export const mockCourses = [
  {
    id: 1,
    name: 'ReactJS Toàn Tập cho Người Mới Bắt Đầu',
    author: 'Hoàng Nguyễn',
    price: 799000,
    level: 'Cơ bản',
    rating: 4.5,
    shortDescription: 'Học ReactJS từ zero đến hero, xây dựng dự án thực tế.',
    longDescription: 'Khóa học này cung cấp kiến thức toàn diện về ReactJS, từ các khái niệm cơ bản như Components, Props, State cho đến các hooks nâng cao và quản lý state với Context API. Học viên sẽ được thực hành qua nhiều dự án nhỏ để củng cố kiến thức.',
    imageUrl: 'https://placehold.co/600x400/3498db/ffffff?text=ReactJS',
  },
  {
    id: 2,
    name: 'Làm Chủ NodeJS & Express trong 10 Tiếng',
    author: 'Trần Anh Tuấn',
    price: 850000,
    level: 'Trung bình',
    rating: 4.8,
    shortDescription: 'Xây dựng RESTful API chuyên nghiệp với NodeJS và Express.',
    longDescription: 'Khóa học tập trung vào việc xây dựng backend mạnh mẽ với NodeJS. Bạn sẽ học cách thiết kế API, làm việc với database MongoDB, xác thực người dùng với JWT và triển khai ứng dụng lên server.',
    imageUrl: 'https://placehold.co/600x400/2ecc71/ffffff?text=NodeJS',
  },
  {
    id: 3,
    name: 'Thiết Kế UI/UX Hiện Đại với Figma',
    author: 'Lê Thảo My',
    price: 499000,
    level: 'Mọi cấp độ',
    rating: 4.7,
    shortDescription: 'Từ ý tưởng đến prototype tương tác được với Figma.',
    longDescription: 'Khóa học này dành cho bất kỳ ai muốn học về thiết kế giao diện người dùng. Chúng ta sẽ đi qua toàn bộ quy trình thiết kế, từ wireframing, visual design, đến tạo prototype và handover cho đội ngũ lập trình.',
    imageUrl: 'https://placehold.co/600x400/9b59b6/ffffff?text=Figma',
  },
  {
    id: 4,
    name: 'Python cho Khoa Học Dữ Liệu',
    author: 'Phạm Văn Khoa',
    price: 1200000,
    level: 'Nâng cao',
    rating: 4.9,
    shortDescription: 'Phân tích và trực quan hóa dữ liệu với Pandas, Matplotlib.',
    longDescription: 'Đi sâu vào các thư viện mạnh mẽ nhất của Python cho khoa học dữ liệu. Khóa học bao gồm các kỹ thuật xử lý dữ liệu lớn, xây dựng mô hình machine learning đơn giản và tạo ra các biểu đồ trực quan, có ý nghĩa.',
    imageUrl: 'https://placehold.co/600x400/f1c40f/ffffff?text=Python',
  },
  {
    id: 5,
    name: 'Tiếng Anh Giao Tiếp Cho Người Đi Làm',
    author: 'Jessica Chen',
    price: 650000,
    level: 'Cơ bản',
    rating: 4.6,
    shortDescription: 'Tự tin giao tiếp trong môi trường công sở quốc tế.',
    longDescription: 'Cải thiện kỹ năng nghe, nói, và phát âm qua các tình huống giao tiếp thực tế trong công việc như họp, thuyết trình, viết email. Giáo trình được biên soạn bởi các chuyên gia ngôn ngữ.',
    imageUrl: 'https://placehold.co/600x400/e74c3c/ffffff?text=English',
  },
  {
    id: 6,
    name: 'Quản Lý Dự Án với Agile và Scrum',
    author: 'David Trần',
    price: 950000,
    level: 'Trung bình',
    rating: 4.8,
    shortDescription: 'Tối ưu hóa quy trình làm việc nhóm và hiệu suất dự án.',
    longDescription: 'Học cách áp dụng phương pháp Agile và framework Scrum vào quản lý dự án phần mềm. Khóa học bao gồm các vai trò, sự kiện, và công cụ trong Scrum, giúp bạn trở thành một Scrum Master hoặc Product Owner hiệu quả.',
    imageUrl: 'https://placehold.co/600x400/1abc9c/ffffff?text=Agile',
  },
];

export const priceFilters = [
    { key: 'all', label: 'Tất cả' },
      { key: '<500', label: '< 500K' },
      { key: '500-1000', label: '500K - 1tr' },
      { key: '>1000', label: '> 1tr' },
]